[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
dirs = "6.0.0"
ratatui = "0.29.0"
crossterm = "0.29.0"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
